server {
    listen 80;

    location /media/ {
        alias /media/;
    }

    # React static
    location /static/js/ {
        alias /backend_static/static/js/;
    }

    location /static/css/ {
        alias /backend_static/static/css/;
    }

    location /static/media/ {
        alias /backend_static/static/media/;
    }

    # Django admin + DRF static
    location /static/admin/ {
        alias /backend_static/admin/;
    }

    location /static/rest_framework/ {
        alias /backend_static/rest_framework/;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /backend_static;
        index index.html;
        try_files $uri /index.html;
    }
}